### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by ChrisEvisi** [MathewHDYT/MathewHDYT#1]
Kia ora (hi) @MathewHDYT ,  
I hope all is great for you.  
I saw you've been adding a lot of value to the TB ArduinoSDK project.  
We have a ESP32-TB project and looking for a assistance.  Is this something you might be interested in or know of anyone who might be?  
Is a APSTA implementation with multi UDP connections on the control side and multi MQTT connections on the TB side.  As well as the standard RPC, telemetry etc.  Theres also a modbusRTU connection for telemetry collection too.  
We have a custom ESP32 board being created at the moment.  
Let me know either way if possible.  
Chris Olson
New Zealand.

**Comment by MathewHDYT** [comment]
@ChrisEvisi Thanks a lot for the kind offer, sadly I do not have the capacity to work on a full or part time project. I currently study full-time for collage and just had holidays and tests, that is why I had some time to work on my own project, which uses the ThingsBoard Arduino SDK. But I do not have the time to work full-time on another project any time soon.

If it is helpful tough I attached some links, which I've used for the mentioned above topics, when using an ESP32. Sadly I do not have the same use-case so I'm not sure this will be a perfect fit, but I think some of them might be helpful. Good luck with your project and I hope it goes well :D.

**ModbusRTU:**
- [eModbus](https://github.com/eModbus/eModbus) - Very good library that is still worked on and has a well written code base and is well documented. Just ensure to read this [issue](https://github.com/eModbus/eModbus/issues/268), because previously the underlying Arduino code caused problems it seems to have been fixed tough since Arduino Version 2.0.6 and when using the changes mentioned in the [issue](https://github.com/eModbus/eModbus/issues/268)

**ThingsBoard (MQTT):**
- For [ThingsBoard](https://github.com/thingsboard/thingsboard-arduino-sdk), thanks to the upgrades all features should now work correctly, especially with an `ESP32` because that's the device I use myself. So everything you could do with your device is implemented (OTA, Provisioning, etc.). Just have a look at the corresponding examples and it should help getting you started.
- Additionally if you need to send as multiple devices I would recommend simply using multiple `ThingsBoard` instances

**UDP:**
- I never really used `UDP`, besides getting an `NTP` timestamp, but I would probably recommend simply using the one in the Arduino base library

**Comment by ChrisEvisi** [comment]
Thanks very much for all your advice Mathew.  
Best wishes for this year at College.  
Chris
